/**
 * HELPER FUNCTIONS FOR THE FLEET GENERATOR.
 *
 * DO NOT EDIT THIS FILE
 */
const randomBearing = bearing => bearing ? bearing + (Math.random() - 0.5) * 90 : Math.random() * 360 // if a bearing is passed it can vary by ± 90°, otherwise it's random
const randomRadius = () => Math.random() * 30

const nextPosition = ([lng, lat], bearing, distanceKm) => {
  const R = 6371; // Earth Radius in Km
  const lat2 = Math.asin(Math.sin(Math.PI / 180 * lat) * Math.cos(distanceKm / R) + Math.cos(Math.PI / 180 * lat) * Math.sin(distanceKm / R) * Math.cos(Math.PI / 180 * bearing));
  const lon2 = Math.PI / 180 * lng + Math.atan2(Math.sin( Math.PI / 180 * bearing) * Math.sin(distanceKm / R) * Math.cos( Math.PI / 180 * lat ), Math.cos(distanceKm / R) - Math.sin( Math.PI / 180 * lat) * Math.sin(lat2));
  return [180 / Math.PI * lon2, 180 / Math.PI * lat2]
}

const randomPos = lngLat => nextPosition(lngLat, randomBearing(), randomRadius())

module.exports = {
  randomBearing,
  nextPosition,
  randomPos,
}
